-- CRIAR TABELA DEPARTAMENTO
CREATE TABLE T_SGC_DEPARTAMENTO
(
    CD_DEPTO    NUMBER(3)       NOT NULL,
    NM_DEPTO    VARCHAR2(30)    NOT NULL
);

-- ADICIONAR A CONSTRAINT CHAVE PRIMARIA
    ALTER TABLE T_SGC_DEPARTAMENTO 
ADD CONSTRAINT PK_SGC_DEPARTAMENTO 
    PRIMARY KEY (CD_DEPTO);
    
-- CRIAR TABELA CARGO
CREATE TABLE T_SGC_CARGO
(
    CD_CARGO           NUMBER(5)       NOT NULL,
    CD_DEPTO           NUMBER(3)       NOT NULL,
    NM_CARGO           VARCHAR2(25)    NOT NULL  
);

-- ADICIONAR A CONSTRAINT CHAVE PRIMARIA
    ALTER TABLE T_SGC_CARGO
ADD CONSTRAINT PK_SGC_CARGO 
    PRIMARY KEY (CD_CARGO); 

-- ADICIONAR A CONSTRAINT CHAVE ESTRANGEIRA
   ALTER TABLE T_SGC_CARGO 
ADD CONSTRAINT FK_SGC_CARGO_DEPTO
    FOREIGN KEY (CD_DEPTO) 
    REFERENCES T_SGC_DEPARTAMENTO (CD_DEPTO); 
    
-- CRIAR TABELA GESTOR
CREATE TABLE T_SGC_GESTOR
(
    NR_MTRGESTOR        NUMBER(5)       NOT NULL,
    NM_GESTOR           VARCHAR2(50)    NOT NULL,
    CD_DEPTO            NUMBER(3)       NOT NULL,
    DS_GENERO           VARCHAR2(10)        NULL,
    NR_TELEFONE         NUMBER(11)          NULL,
    DS_EMAIL            VARCHAR2(25)    NOT NULL,
    DT_ADMISSAO         DATE            NOT NULL
);

-- ADICIONAR A CONSTRAINT CHAVE PRIMARIA
    ALTER TABLE T_SGC_GESTOR
ADD CONSTRAINT PK_SGC_GESTOR 
    PRIMARY KEY (NR_MTRGESTOR); 

-- ADICIONAR A CONSTRAINT CHAVE ESTRANGEIRA
   ALTER TABLE T_SGC_GESTOR 
ADD CONSTRAINT FK_SGC_GESTOR_DEPTO
    FOREIGN KEY (CD_DEPTO) 
    REFERENCES T_SGC_DEPARTAMENTO (CD_DEPTO); 

-- CRIAR TABELA FUNCIONARIO
CREATE TABLE T_SGC_FUNCIONARIO
(
    NR_MTRFUNC          NUMBER(5)       NOT NULL,
    NM_FUNC             VARCHAR2(50)    NOT NULL,
    CD_DEPTO            NUMBER(3)       NOT NULL,
    DS_GENERO           VARCHAR2(10)        NULL,
    NR_TELEFONE         NUMBER(11)          NULL,
    DS_EMAIL            VARCHAR2(25)    NOT NULL,
    DT_ADMISSAO         DATE            NOT NULL,
    QT_PONTUACAO        NUMBER(3)       NOT NULL
);

-- ADICIONAR A CONSTRAINT CHAVE PRIMARIA
    ALTER TABLE T_SGC_FUNCIONARIO
ADD CONSTRAINT PK_SGC_FUNCIONARIO 
    PRIMARY KEY (NR_MTRFUNC); 

-- ADICIONAR A CONSTRAINT CHAVE ESTRANGEIRA
   ALTER TABLE T_SGC_FUNCIONARIO
ADD CONSTRAINT FK_SGC_FUNC_DEPTO
    FOREIGN KEY (CD_DEPTO) 
    REFERENCES T_SGC_DEPARTAMENTO (CD_DEPTO);


-- CRIAR TABELA MISSAO
CREATE TABLE T_SGC_MISSAO
(
    CD_MISSAO           NUMBER(5)       NOT NULL,
    DS_MISSAO           VARCHAR2(500)   NOT NULL,
    DT_CADASTRO         DATE            NOT NULL,
    CD_DEPTO            NUMBER(3)       NOT NULL,
    NR_MTRGESTOR        NUMBER(5)       NOT NULL,
    NR_MTRFUNC          NUMBER(5)       NOT NULL,
    DS_STATUS           VARCHAR2(10)    NOT NULL,
    QT_VALOR            NUMBER(3)       NOT NULL,
    DT_TERMINO          DATE            NOT NULL
);

-- ADICIONAR A CONSTRAINT CHAVE PRIMARIA
    ALTER TABLE T_SGC_MISSAO
ADD CONSTRAINT PK_SGC_MISSAO 
    PRIMARY KEY (CD_MISSAO); 

-- ADICIONAR A CONSTRAINT CHAVE ESTRANGEIRA
   ALTER TABLE T_SGC_MISSAO
ADD CONSTRAINT FK_SGC_MISSAO_FUNC
    FOREIGN KEY (NR_MTRFUNC) 
    REFERENCES T_SGC_FUNCIONARIO (NR_MTRFUNC);
    
    ALTER TABLE T_SGC_MISSAO
ADD CONSTRAINT FK_SGC_MISSAO_GESTOR
    FOREIGN KEY (NR_MTRGESTOR) 
    REFERENCES T_SGC_GESTOR (NR_MTRGESTOR);
    
    ALTER TABLE T_SGC_MISSAO
ADD CONSTRAINT FK_SGC_MISSAO_DEPTO
    FOREIGN KEY (CD_DEPTO) 
    REFERENCES T_SGC_DEPARTAMENTO (CD_DEPTO);